### ISSUE TITLE
Error when stac_extensions (or collection) is not present

### ISSUE THREAD

**Issue by m-mohr** [TomAugspurger/stac-geoparquet#12]
If the items don't have a `stac_extensions` entry (which is valid), I get an error:

```
Traceback (most recent call last):
  File "/home/mm/.local/bin/stac", line 8, in <module>
    sys.exit(run_cli())
  File "/home/mm/.local/lib/python3.10/site-packages/stactools/cli/cli.py", line 37, in run_cli
    cli(prog_name="stac")
  File "/home/mm/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mm/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mm/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mm/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mm/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mm/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/mm/.local/lib/python3.10/site-packages/stactools/geoparquet_items/commands.py", line 58, in create_command
    df = stac_geoparquet.to_geodataframe(items)
  File "/home/mm/.local/lib/python3.10/site-packages/stac_geoparquet/stac_geoparquet.py", line 79, in to_geodataframe
    gdf = pd.concat([gdf[columns], gdf.drop(columns=columns)], axis="columns")
  File "/home/mm/.local/lib/python3.10/site-packages/geopandas/geodataframe.py", line 1475, in __getitem__
    result = super().__getitem__(key)
  File "/home/mm/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3767, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/mm/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5877, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/mm/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5941, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['stac_extensions'] not in index"
```

I assume something similar will occur for the `collection` property.

Looking into it right now, but want to persist the issue already.

**Comment by TomAugspurger** [comment]
Ah, I didn't realize it was optional.

At https://github.com/TomAugspurger/stac-geoparquet/blob/main/stac_geoparquet/stac_geoparquet.py#L68, we'd need something like `columns = set(["type", ...]) & set(df.columns))`.

**Comment by m-mohr** [comment]
Thanks, PR incoming...

**Comment by m-mohr** [comment]
Please see PR #13
